packages:
  - api/*
  - examples/*
  - examples/web-platform/packages/*
  - examples/with-solidjs/packages/*

strictPeerDependencies: true
engineStrict: true

# We are using flatten config of eslint and not using prettier
# Disable the default publicHoistPattern(*-eslint-*, *-prettier-*)
publicHoistPattern: []

allowBuilds:
  "@parcel/watcher": true
  core-js: false
  dprint: true
  esbuild: true

catalog:
  "@lynx-js/external-bundle-rsbuild-plugin": "0.4.1"
  "@lynx-js/lynx-bundle-rslib-config": "https://pkg.pr.new/lynx-family/lynx-stack/@lynx-js/lynx-bundle-rslib-config@13bb6a9"
  "@lynx-js/rsbuild-plugin": "https://pkg.pr.new/lynx-family/lynx-stack/@lynx-js/rsbuild-plugin@13bb6a9"
  "@lynx-js/react-umd": "0.125.0"
  "@lynx-js/qrcode-rsbuild-plugin": "0.6.0"
  "@lynx-js/react-use": "0.2.2"
  "@lynx-js/react": "0.125.0"
  "@lynx-js/react-rsbuild-plugin": "https://pkg.pr.new/lynx-family/lynx-stack/@lynx-js/react-rsbuild-plugin@13bb6a9"
  "@lynx-js/rspeedy": "https://pkg.pr.new/lynx-family/lynx-stack/@lynx-js/rspeedy@13bb6a9"
  "@lynx-js/types": "4.1.0"
  "@lynx-js/template-webpack-plugin": "0.15.2"
  "@lynx-js/testing-environment": "0.3.3"
  "@lynx-js/type-element-api": "0.0.10"
  "@lynx-js/vanilla-rsbuild-plugin": "0.0.2"
  "@lynx-js/runtime-wrapper-webpack-plugin": "0.2.3"
  "@lynx-js/config-rsbuild-plugin": "0.2.2"
  "@rsbuild/plugin-sass": "2.0.1"

minimumReleaseAgeExclude:
  - "@lynx-js/*"
  - "@dprint/*"
  - dprint@0.57.1
