packages:
  - api/*
  - examples/*
  - examples/web-platform/packages/*
  - examples/with-solidjs/packages/*

catalog:
  "@lynx-js/qrcode-rsbuild-plugin": "0.4.2"
  "@lynx-js/rspeedy": "0.11.8"
  "@lynx-js/react": "0.114.3"
  "@lynx-js/react-rsbuild-plugin": "0.11.3"
  "@lynx-js/types": "3.5.11"
