packages:
  - api/*
  - examples/*
  - examples/web-platform/packages/*
  - examples/with-solidjs/packages/*

allowBuilds:
  core-js: false
  dprint: true
  esbuild: true

catalog:
  "@lynx-js/external-bundle-rsbuild-plugin": "0.4.0"
  "@lynx-js/lynx-bundle-rslib-config": "0.6.0"
  "@lynx-js/react-umd": "0.123.0"
  "@lynx-js/qrcode-rsbuild-plugin": "0.6.0"
  "@lynx-js/react-use": "0.2.1"
  "@lynx-js/react": "0.123.0"
  "@lynx-js/react-rsbuild-plugin": "0.18.0"
  "@lynx-js/rspeedy": "0.16.0"
  "@lynx-js/types": "4.0.0"
  "@lynx-js/template-webpack-plugin": "0.13.0"
  "@lynx-js/type-element-api": "0.0.8"
  "@lynx-js/runtime-wrapper-webpack-plugin": "0.2.1"
  "@lynx-js/config-rsbuild-plugin": "0.1.0"
  "@rsbuild/plugin-less": "2.0.1"
  "@rsbuild/plugin-sass": "2.0.1"
  "@rsbuild/plugin-stylus": "2.0.1"
  "@rsbuild/plugin-typed-css-modules": "1.2.4"

minimumReleaseAgeExclude:
  - "@lynx-js/*"
