packages:
  - api/*
  - examples/*
  - examples/web-platform/packages/*
  - examples/with-solidjs/packages/*

catalog:
  "@lynx-js/qrcode-rsbuild-plugin": "0.3.6"
  "@lynx-js/rspeedy": "0.9.7"
  "@lynx-js/react": "0.109.0"
  "@lynx-js/react-rsbuild-plugin": "0.10.1"
