packages:
  - api/*
  - examples/*
  - examples/web-platform/packages/*
  - examples/with-solidjs/packages/*

catalog:
  "@lynx-js/qrcode-rsbuild-plugin": "0.4.3"
  "@lynx-js/rspeedy": "0.12.5"
  "@lynx-js/react": "0.115.3"
  "@lynx-js/react-rsbuild-plugin": "0.12.4"
  "@lynx-js/types": "3.6.0"
  "@lynx-js/template-webpack-plugin": "0.10.1"
