packages:
  - api/*
  - examples/*
  - examples/web-platform/packages/*
  - examples/with-solidjs/packages/*

catalog:
  "@lynx-js/qrcode-rsbuild-plugin": "0.4.1"
  "@lynx-js/rspeedy": "0.11.1"
  "@lynx-js/react": "0.112.6"
  "@lynx-js/react-rsbuild-plugin": "0.10.13"
