/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ARouteImport } from "./routes/a";
import { Route as BRouteImport } from "./routes/b";
import { Route as IndexRouteImport } from "./routes/index";

const BRoute = BRouteImport.update({
  id: "/b",
  path: "/b",
  getParentRoute: () => rootRouteImport,
} as any);
const ARoute = ARouteImport.update({
  id: "/a",
  path: "/a",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/a": typeof ARoute;
  "/b": typeof BRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/a": typeof ARoute;
  "/b": typeof BRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/a": typeof ARoute;
  "/b": typeof BRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/a" | "/b";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/a" | "/b";
  id: "__root__" | "/" | "/a" | "/b";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ARoute: typeof ARoute;
  BRoute: typeof BRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/b": {
      id: "/b";
      path: "/b";
      fullPath: "/b";
      preLoaderRoute: typeof BRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/a": {
      id: "/a";
      path: "/a";
      fullPath: "/a";
      preLoaderRoute: typeof ARouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ARoute: ARoute,
  BRoute: BRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
