// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  avatar: string;
  button: string;
  caption: string;
  card: string;
  divider: string;
  header: string;
  initial: string;
  label: string;
  page: string;
  primary: string;
  row: string;
  secondary: string;
  subtitle: string;
  title: string;
  value: string;
}
declare const cssExports: CssExports;
export default cssExports;
