// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  avatar: string;
  card: string;
  divider: string;
  header: string;
  initial: string;
  label: string;
  page: string;
  row: string;
  rows: string;
  subtitle: string;
  title: string;
  value: string;
}
declare const cssExports: CssExports;
export default cssExports;
