// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

import { pluginQRCode } from "@lynx-js/qrcode-rsbuild-plugin";
import { pluginReactLynx } from "@lynx-js/react-rsbuild-plugin";
import { defineConfig } from "@lynx-js/rspeedy";
import { pluginSass } from "@rsbuild/plugin-sass";
import { pluginTypeCheck } from "@rsbuild/plugin-type-check";

export default defineConfig({
  source: {
    entry: {
      "-x-auto-font-size-preset-sizes": "./src/-x-auto-font-size-preset-sizes/App.tsx",
      "-x-auto-font-size": "./src/-x-auto-font-size/App.tsx",
      "-x-handle-color": "./src/-x-handle-color/App.tsx",
      "-x-handle-size": "./src/-x-handle-size/App.tsx",
      "align-content": "./src/align-content/App.tsx",
      "align-items": "./src/align-items/App.tsx",
      "align-self": "./src/align-self/App.tsx",
      "animation": "./src/animation/App.tsx",
      "animation-delay": "./src/animation-delay/App.tsx",
      "animation-direction": "./src/animation-direction/App.tsx",
      "animation-duration": "./src/animation-duration/App.tsx",
      "animation-fill-mode": "./src/animation-fill-mode/App.tsx",
      "animation-iteration-count": "./src/animation-iteration-count/App.tsx",
      "animation-name": "./src/animation-name/App.tsx",
      "animation-play-state": "./src/animation-play-state/App.tsx",
      "animation-timing-function": "./src/animation-timing-function/App.tsx",
      "aspect-ratio": "./src/aspect-ratio/App.tsx",
      "background": "./src/background/App.tsx",
      "background-clip": "./src/background-clip/App.tsx",
      "background-color": "./src/background-color/App.tsx",
      "background-image": "./src/background-image/App.tsx",
      "background-origin": "./src/background-origin/App.tsx",
      "background-position": "./src/background-position/App.tsx",
      "background-repeat": "./src/background-repeat/App.tsx",
      "background-size": "./src/background-size/App.tsx",
      "border": "./src/border/App.tsx",
      "border-bottom": "./src/border-bottom/App.tsx",
      "border-bottom-color": "./src/border-bottom-color/App.tsx",
      "border-bottom-left-radius": "./src/border-bottom-left-radius/App.tsx",
      "border-bottom-right-radius": "./src/border-bottom-right-radius/App.tsx",
      "border-bottom-style": "./src/border-bottom-style/App.tsx",
      "border-bottom-width": "./src/border-bottom-width/App.tsx",
      "border-color": "./src/border-color/App.tsx",
      "border-end-end-radius": "./src/border-end-end-radius/App.tsx",
      "border-end-start-radius": "./src/border-end-start-radius/App.tsx",
      "border-inline-end-color": "./src/border-inline-end-color/App.tsx",
      "border-inline-end-style": "./src/border-inline-end-style/App.tsx",
      "border-inline-end-width": "./src/border-inline-end-width/App.tsx",
      "border-inline-start-color": "./src/border-inline-start-color/App.tsx",
      "border-inline-start-style": "./src/border-inline-start-style/App.tsx",
      "border-inline-start-width": "./src/border-inline-start-width/App.tsx",
      "border-left": "./src/border-left/App.tsx",
      "border-left-color": "./src/border-left-color/App.tsx",
      "border-left-style": "./src/border-left-style/App.tsx",
      "border-left-width": "./src/border-left-width/App.tsx",
      "border-radius": "./src/border-radius/App.tsx",
      "border-right": "./src/border-right/App.tsx",
      "border-right-color": "./src/border-right-color/App.tsx",
      "border-right-style": "./src/border-right-style/App.tsx",
      "border-right-width": "./src/border-right-width/App.tsx",
      "border-start-end-radius": "./src/border-start-end-radius/App.tsx",
      "border-start-start-radius": "./src/border-start-start-radius/App.tsx",
      "border-style": "./src/border-style/App.tsx",
      "border-top": "./src/border-top/App.tsx",
      "border-top-color": "./src/border-top-color/App.tsx",
      "border-top-left-radius": "./src/border-top-left-radius/App.tsx",
      "border-top-right-radius": "./src/border-top-right-radius/App.tsx",
      "border-top-style": "./src/border-top-style/App.tsx",
      "border-top-width": "./src/border-top-width/App.tsx",
      "border-width": "./src/border-width/App.tsx",
      "bottom": "./src/bottom/App.tsx",
      "box-shadow": "./src/box-shadow/App.tsx",
      "box-sizing": "./src/box-sizing/App.tsx",
      "caret-color": "./src/caret-color/App.tsx",
      "color": "./src/color/App.tsx",
      "column-gap": "./src/column-gap/App.tsx",
      "direction": "./src/direction/App.tsx",
      "display": "./src/display/App.tsx",
      "filter": "./src/filter/App.tsx",
      "flex": "./src/flex/App.tsx",
      "flex-basis": "./src/flex-basis/App.tsx",
      "flex-direction": "./src/flex-direction/App.tsx",
      "flex-grow": "./src/flex-grow/App.tsx",
      "flex-shrink": "./src/flex-shrink/App.tsx",
      "flex-wrap": "./src/flex-wrap/App.tsx",
      "flex-flow": "./src/flex-flow/App.tsx",
      "font-family": "./src/font-family/App.tsx",
      "font-feature-settings": "./src/font-feature-settings/App.tsx",
      "font-optical-sizing": "./src/font-optical-sizing/App.tsx",
      "font-size": "./src/font-size/App.tsx",
      "font-style": "./src/font-style/App.tsx",
      "font-variation-settings": "./src/font-variation-settings/App.tsx",
      "font-weight": "./src/font-weight/App.tsx",
      "gap": "./src/gap/App.tsx",
      "grid-auto-columns": "./src/grid-auto-columns/App.tsx",
      "grid-auto-flow": "./src/grid-auto-flow/App.tsx",
      "grid-auto-rows": "./src/grid-auto-rows/App.tsx",
      "grid-column-end": "./src/grid-column-end/App.tsx",
      "grid-column-span": "./src/grid-column-span/App.tsx",
      "grid-column-start": "./src/grid-column-start/App.tsx",
      "grid-row-end": "./src/grid-row-end/App.tsx",
      "grid-row-span": "./src/grid-row-span/App.tsx",
      "grid-row-start": "./src/grid-row-start/App.tsx",
      "grid-template-columns": "./src/grid-template-columns/App.tsx",
      "grid-template-rows": "./src/grid-template-rows/App.tsx",
      "height": "./src/height/App.tsx",
      "image-rendering": "./src/image-rendering/App.tsx",
      "inset-inline-end": "./src/inset-inline-end/App.tsx",
      "inset-inline-start": "./src/inset-inline-start/App.tsx",
      "justify-content": "./src/justify-content/App.tsx",
      "justify-items": "./src/justify-items/App.tsx",
      "justify-self": "./src/justify-self/App.tsx",
      "left": "./src/left/App.tsx",
      "letter-spacing": "./src/letter-spacing/App.tsx",
      "line-height": "./src/line-height/App.tsx",
      "linear-cross-gravity": "./src/linear-cross-gravity/App.tsx",
      "linear-gravity": "./src/linear-gravity/App.tsx",
      "linear-layout-gravity": "./src/linear-layout-gravity/App.tsx",
      "linear-direction": "./src/linear-direction/App.tsx",
      "linear-weight": "./src/linear-weight/App.tsx",
      "linear-weight-sum": "./src/linear-weight-sum/App.tsx",
      "margin": "./src/margin/App.tsx",
      "margin-bottom": "./src/margin-bottom/App.tsx",
      "margin-inline-end": "./src/margin-inline-end/App.tsx",
      "margin-inline-start": "./src/margin-inline-start/App.tsx",
      "margin-left": "./src/margin-left/App.tsx",
      "margin-right": "./src/margin-right/App.tsx",
      "margin-top": "./src/margin-top/App.tsx",
      "mask": "./src/mask/App.tsx",
      "mask-image": "./src/mask-image/App.tsx",
      "max-height": "./src/max-height/App.tsx",
      "max-width": "./src/max-width/App.tsx",
      "min-height": "./src/min-height/App.tsx",
      "min-width": "./src/min-width/App.tsx",
      "opacity": "./src/opacity/App.tsx",
      "order": "./src/order/App.tsx",
      "overflow": "./src/overflow/App.tsx",
      "overflow-x": "./src/overflow-x/App.tsx",
      "overflow-y": "./src/overflow-y/App.tsx",
      "padding": "./src/padding/App.tsx",
      "padding-bottom": "./src/padding-bottom/App.tsx",
      "padding-inline-end": "./src/padding-inline-end/App.tsx",
      "padding-inline-start": "./src/padding-inline-start/App.tsx",
      "padding-left": "./src/padding-left/App.tsx",
      "padding-right": "./src/padding-right/App.tsx",
      "padding-top": "./src/padding-top/App.tsx",
      "perspective": "./src/perspective/App.tsx",
      "position": "./src/position/App.tsx",
      "ppx": "./src/ppx/App.tsx",
      "relative-align-bottom": "./src/relative-align-bottom/App.tsx",
      "relative-align-inline-end": "./src/relative-align-inline-end/App.tsx",
      "relative-align-inline-start": "./src/relative-align-inline-start/App.tsx",
      "relative-align-left": "./src/relative-align-left/App.tsx",
      "relative-align-right": "./src/relative-align-right/App.tsx",
      "relative-align-top": "./src/relative-align-top/App.tsx",
      "relative-bottom-of": "./src/relative-bottom-of/App.tsx",
      "relative-center": "./src/relative-center/App.tsx",
      "relative-id": "./src/relative-id/App.tsx",
      "relative-inline-end-of": "./src/relative-inline-end-of/App.tsx",
      "relative-inline-start-of": "./src/relative-inline-start-of/App.tsx",
      "relative-layout-once": "./src/relative-layout-once/App.tsx",
      "relative-left-of": "./src/relative-left-of/App.tsx",
      "relative-right-of": "./src/relative-right-of/App.tsx",
      "relative-top-of": "./src/relative-top-of/App.tsx",
      "right": "./src/right/App.tsx",
      "row-gap": "./src/row-gap/App.tsx",
      "text-align": "./src/text-align/App.tsx",
      "text-decoration": "./src/text-decoration/App.tsx",
      "text-indent": "./src/text-indent/App.tsx",
      "text-overflow": "./src/text-overflow/App.tsx",
      "text-shadow": "./src/text-shadow/App.tsx",
      "text-stroke": "./src/text-stroke/App.tsx",
      "text-stroke-color": "./src/text-stroke-color/App.tsx",
      "text-stroke-width": "./src/text-stroke-width/App.tsx",
      "top": "./src/top/App.tsx",
      "transform": "./src/transform/App.tsx",
      "transform-origin": "./src/transform-origin/App.tsx",
      "transition": "./src/transition/App.tsx",
      "transition-delay": "./src/transition-delay/App.tsx",
      "transition-duration": "./src/transition-duration/App.tsx",
      "transition-property": "./src/transition-property/App.tsx",
      "transition-timing-function": "./src/transition-timing-function/App.tsx",
      "vertical-align": "./src/vertical-align/App.tsx",
      "visibility": "./src/visibility/App.tsx",
      "white-space": "./src/white-space/App.tsx",
      "width": "./src/width/App.tsx",
      "word-break": "./src/word-break/App.tsx",
      "z-index": "./src/z-index/App.tsx",
      clip_path_circle: "./src/clip_path/circle",
      clip_path_inset: "./src/clip_path/inset",
      clip_path_ellipse: "./src/clip_path/ellipse",
      clip_path_path: "./src/clip_path/path",
    },
  },
  plugins: [
    pluginReactLynx({
      enableCSSInheritance: true,
      defaultDisplayLinear: false,
    }),
    pluginSass({}),
    pluginQRCode(),
    pluginTypeCheck(),
  ],
  output: {
    assetPrefix: "https://lynxjs.org/lynx-examples/css-api/dist",
  },
});
